# Generated by Django 4.0 on 2024-07-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='cnpj')),
                ('contato', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pis', models.CharField(max_length=255)),
                ('jornada', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('contato_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_email', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_nascimento', models.DateTimeField(blank=True, null=True)),
                ('dt_entrada', models.DateTimeField(blank=True, null=True)),
                ('dt_saida', models.DateTimeField(blank=True, null=True)),
                ('custo_beneficios', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('custo_salario', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('custo_bruto', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.cargos')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.empresas')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.status')),
                ('turnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.turnos')),
            ],
        ),
    ]
