# Generated by Django 4.0 on 2024-08-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('valorizacao', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.empresas')),
            ],
        ),
    ]
