# Generated by Django 4.0 on 2024-08-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staffs', '0002_fechamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('contato_email', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.empresas')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.person')),
            ],
        ),
    ]
