# Generated by Django 4.0 on 2024-08-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_person_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='valor_acao',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
