# Generated by Django 4.0 on 2024-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_carteira_quantidade_carteira_valor_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentos',
            name='valorizacao',
        ),
        migrations.AlterField(
            model_name='fechamentos',
            name='valor_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
