# Generated by Django 4.0 on 2024-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_remove_fechamentos_valorizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentos',
            name='valorizacao',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
