# Generated by Django 4.0 on 2024-08-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_fechamentos_valorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentos',
            name='porcentagem',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
