# Generated by Django 4.0 on 2024-08-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_fechamentos_porcentagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechamentos',
            old_name='valorizacao',
            new_name='variação',
        ),
    ]
