# Generated by Django 4.0 on 2023-08-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EA', 'Em andamento'), ('F', 'Finalizado')], max_length=2)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('grandeza', models.CharField(choices=[('Un', 'Unidade'), ('Kg', 'kilograma'), ('L', 'litros')], max_length=4)),
                ('codigo', models.CharField(max_length=255)),
                ('validade', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.tipoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.producao')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.produtos')),
            ],
        ),
    ]
