# Generated by Django 4.0 on 2023-08-18 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='producaoitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='producao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producaoitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
