# Generated by Django 4.0 on 2023-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_producao_options_alter_producaoitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='validade',
        ),
        migrations.AddField(
            model_name='produtos',
            name='validade_dias',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
