# Generated by Django 4.0 on 2023-09-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_alter_producaoitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.produtos')),
            ],
        ),
    ]
