# Generated by Django 4.0 on 2023-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='entrada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
