# Generated by Django 4.0 on 2023-08-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0002_alter_entrada_options_entrada_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo_insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materia_prima.insumos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
