# Generated by Django 4.0 on 2023-08-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0003_estoqueinsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='producao',
        ),
    ]
