# Generated by Django 4.0 on 2023-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_prima', '0004_remove_entrada_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='contato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
