# Generated by Django 4.0 on 2023-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saidas', '0002_alter_saida_options_saida_dt_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='producao',
        ),
        migrations.AddField(
            model_name='saida',
            name='id_ref',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='ref',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
